#####
# r6t's Home Assistant base config. Active components not configured here were automatically added via Home Assistant discovery. Example: hue lights
#####
homeassistant:
#  customize: !include customize.yaml
  elevation: !secret elevation
  latitude: !secret latitude
  longitude: !secret longitude
  name: !secret hass_name
  time_zone: !secret time_zone
  unit_system: imperial

#####
# Home Assistant config files
#####
# all automation moved to appdaemon
# automation: !include automations.yaml 
# script: !include scripts.yaml

#####
# Home Assistant Components
#####
api: !include components/api.yaml
binary_sensor: !include components/binary_sensor.yaml
cloud: !include components/cloud.yaml
config:
conversation:
discovery:
frontend:
history:
http: !include components/http.yaml
input_boolean: !include components/input_boolean.yaml
# input_number: !include components/input_number.yaml
logger:
logbook:
lovelace: !include components/lovelace.yaml
map:
notify: !include components/notify.yaml
recorder:
sensor: !include components/sensors.yaml
sun:
system_health:
updater:

#####
# External Components
#####
camera: !include components/camera.yaml
nest: !include components/nest.yaml
sonos:
telegram_bot: !include components/telegram_bot.yaml
vacuum: !include components/vacuum.yaml

