#####
# r6t's Home Assistant base config
#####
homeassistant:
#  customize: !include customize.yaml
  elevation: !secret elevation
  latitude: !secret latitude
  longitude: !secret longitude
  name: !secret hass_name
  time_zone: !secret time_zone
  unit_system: imperial

#####
# Home Assistant config files
#####
automation: !include automations.yaml
script: !include scripts.yaml

#####
# Home Assistant Components
#####
api: !include components/api.yaml
binary_sensor: !include components/binary_sensor.yaml
cloud: !include components/cloud.yaml
config:
discovery: # discovered components listed at bottom of file
frontend:
history:
http: !include components/http.yaml
input_boolean: !include components/input_boolean.yaml
# input_number: !include components/input_number.yaml
logger:
logbook:
map:
recorder:
sensor: !include components/sensors.yaml
sun:
system_health:
updater:

#####
# External Components
#####
nest: !include components/nest.yaml
sonos:
vacuum: !include components/vacuum.yaml
xiaomi_aqara: !include components/xiaomi_aqara.yaml

#####
# Components automatically added via discovery
#####
# hue
