homeassistant:
#  customize: !include customize.yaml
  elevation: !secret elevation
  latitude: !secret latitude
  longitude: !secret longitude
  name: !secret hass_name
  time_zone: !secret time_zone
  unit_system: imperial

#####
# Home Assistant Config Files
##### 
automation: !include automations.yaml
# group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

#####
# Home Assistant Components
#####
api: !include components/api.yaml
binary_sensor: !include components/binary_sensor.yaml
cloud: !include components/cloud.yaml
config:
discovery:
frontend:
history:
http: !include components/http.yaml
input_boolean: !include components/input_boolean.yaml
input_number: !include components/input_number.yaml
logger:
logbook:
map:
recorder:
updater:

#####
# External Components
#####
device_tracker: !include components/device_tracker.yaml
fan: !include components/fan.yaml
hue:
media_player: !include components/media_players.yaml
nest: !include components/nest.yaml
notify: !include components/notify.yaml
sensor: !include components/sensors.yaml
shell_command: !include components/shell_command.yaml
# sonos: !include components/sonos.yaml 
sun:
telegram_bot: !include components/telegram_bot.yaml
tts: !include components/tts.yaml
vacuum: !include components/vacuum.yaml
weather: !include components/weather.yaml
xiaomi_aqara: !include components/xiaomi_aqara.yaml

#####
# Component Graveyard
#####
# alexa:
# eight_sleep: !include components/eight_sleep.yaml
# mqtt:
#   broker: !secret mqtt_broker
#   port: !secret mqtt_port
#   username: !secret mqtt_user
#   password: !secret mqtt_password

# camera:
#   - platform: uvc
#     nvr: !secret unifi_camera
# usps:
#   username: !secret usps_user
#   password: !secret usps_password
#   driver: phantomjs

# zwave:
#   usb_path: /dev/ttyACM0

#     key: unifi_camera_api_key
#     password: unifi_camera_password

# cast:
